title: Code25Y
author: Song seung yul
email: thinkdiff@uuh.ulsan.kr
description: >-
  공부한 것과 공부할 것을 마크다운으로 기록하고 쌓아두는 개인 학습 노트 블로그.
baseurl: "/Code25Y"
url: "https://songseungyul.github.io"
lang: ko-KR
timezone: Asia/Seoul
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
minima:
  skin: auto
